

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int questions;	/*The amount of questions chosen by user*/
int difficulty;	/*The difficulty level chosen by user*/
int answer;		/*The answer to the question*/
int right;		/*counter for number correct*/

int genQuestion();			/*prototype*/
int answerQuestion(int);	/*prototype*/
void response(int);			/*prototype*/

int main(void)
{
    int x;													/*counter for for method*/
    int quest;												/*variable for storage of answer generated by genQuestion function*/
    do
    {
	printf("How many questions for this test? (1-20)? ");	/*asks this until proper answer given*/
	scanf("%d",&questions);
    }
    while(questions < 1 || questions > 20);

    do
    {
	printf("Please select the difficulty (1-4): ");			/*asks this until proper answer given*/
	scanf("%d",&difficulty);
    }
    while(difficulty < 1 || difficulty > 4);

    for(x=1; x<=questions; x++)
    {
        printf("Question %d: ",x);
        quest=genQuestion();								/*stored answer into quest variable*/
        printf("=\n");
        response(answerQuestion(quest));					/*calls on the answerQuestion function with the quest variable
															  and passes that integer to the response function*/
    }

    printf("Your score was %d/%d\n",right,questions);

	getchar();												/*two calls to getchar() because the scanf() leaves the newline 
															character \n that you entered after numbers in the input stream. 
															The first getchar() read that \n and the next getchar() waits 
															for you to hit newline again.*/
	getchar();

    return (0);
}

int genQuestion()											/*Used to randomly generate and output a random question based 
															upon a difficulty which is passed as a parameter. Returns the 
															answer of the question.*/
{
	int num1=0;												/*first random number*/
	int num2=0;												/*second random number*/
	int oper=0;												/*random number to determine operator*/

	srand(time(NULL));										/*used to generate different random number each time based on 
															computer's time*/
	if(difficulty == 1)
	{
		num1=1 + rand() % 10;								/*generate random number 1-10*/
		num2=1 + rand() % 10;
		oper=1 + rand() % 4;

		if(oper==1)
		{
                    answer=num1 + num2;
                    printf("%d + %d",num1,num2);

                }
                else if(oper==2)
                {
                    answer=num1 - num2;
                    printf("%d - %d",num1,num2);
                }
                else if(oper==3)
                {
                    answer=num1 * num2;
                    printf("%d * %d",num1,num2);
                }
                else
                {
                    if(num2==0)
                    {
                        answer=num2 / num1;
                        printf("%d / %d",num2,num1);
                    }
                    else
                    {
                        answer=num1 / num2;
                        printf("%d / %d",num1,num2);
                    }
                }
	}
	else if(difficulty == 2)								/*generate random number 1-50*/
	{
		num1=1 + rand() % 50;									
		num2=1 + rand() % 50;
                oper=1 + rand() % 4;

		if(oper==1)
		{
                    answer=num1 + num2;
                    printf("%d + %d",num1,num2);

                }
                else if(oper==2)
                {
                    answer=num1 - num2;
                    printf("%d - %d",num1,num2);
                }
                else if(oper==3)
                {
                    answer=num1 * num2;
                    printf("%d * %d",num1,num2);
                }
                else
                {
                    if(num2==0)
                    {
                        answer=num2 / num1;
                        printf("%d / %d",num2,num1);
                    }
                    else
                    {
                        answer=num1 / num2;
                        printf("%d / %d",num1,num2);
                    }
                }
	}
	else if(difficulty == 3)								/*generate random number 1-100*/
	{
		num1=1 + rand() % 100;
		num2=1 + rand() % 100;
                oper=1 + rand() % 4;

		if(oper==1)
		{
                    answer=num1 + num2;
                    printf("%d + %d",num1,num2);

                }
                else if(oper==2)
                {
                    answer=num1 - num2;
                    printf("%d - %d",num1,num2);
                }
                else if(oper==3)
                {
                    answer=num1 * num2;
                    printf("%d * %d",num1,num2);
                }
                else
                {
                    if(num2==0)
                    {
                        answer=num2 / num1;
                        printf("%d / %d",num2,num1);
                    }
                    else
                    {
                        answer=num1 / num2;
                        printf("%d / %d",num1,num2);
                    }
                }
	}
	else													/*generate random number -100 - 100*/
	{
		num1=-100 + rand() % 100;
		num2=-100 + rand() % 100;
                oper=1 + rand() % 4;

		if(oper==1)
		{
                    answer=num1 + num2;
                    printf("%d + %d",num1,num2);

                }
                else if(oper==2)
                {
                    answer=num1 - num2;
                    printf("%d - %d",num1,num2);
                }
                else if(oper==3)
                {
                    answer=num1 * num2;
                    printf("%d * %d",num1,num2);
                }
                else
                {
                    if(num2==0)
                    {
                        answer=num2 / num1;
                        printf("%d / %d",num2,num1);
                    }
                    else
                    {
                        answer=num1 / num2;
                        printf("%d / %d",num1,num2);
                    }
                }
	}
	return answer;
}

int answerQuestion(int answer)								/*Prompts user for an answer, checks if it is correct based on the
															correct answer, which is passed to the function as a parameter.
    														Returns an indicator of whether or not the answer was correct.*/
{
		int userAnswer;

        printf("Please enter your answer: ");
		scanf("%d",&userAnswer);
        if (answer==userAnswer)								/*if answer is correct, return 1 and increment right*/
        {
            right++;
            return 1;
        }
        else												/*If answer is wrong return 0*/
        {
            return 0;
        }
}

void response(int correct)									/*Outputs a response to the user’s answer based upon a passed parameter
															which indicates whether the answer was correct or incorrect. The function 
															randomly selects one of the three responses, either from the correct 
															responses or the incorrect responses*/

{
    int response = 1 + rand() % 3;

    if (correct)
    {
        if(response==1)
        {
            printf("Nice!\n");
        }
        else if(response==2)
        {
            printf("Good Job!\n");
        }
        else
        {
            printf("Perfect!\n");
        }
    }
    else
    {
        if(response==1)
        {
            printf("I don't think so!\n");
            printf("The correct answer is: %d\n",answer);
        }
        else if(response==2)
        {
            printf("Better luck next time!\n");
            printf("The correct answer is: %d\n",answer);
        }
        else
        {
            printf("Oopsie!\n");
            printf("The correct answer is: %d\n",answer);
        }
    }
}


